apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${namespace}
  namespace: ${namespace}
spec:
  secretName: ${domain}-wildcard-certificate
  ClusterissuerRef:
    name: letsencrypt
  commonName: ${domain}
  dnsNames:
    - "*.${domain}"
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - ${domain}
          - "*.${domain}"
