apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ${namespace}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${email_address}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: ${domain}-wildcard-key

    # ACME DNS-01 provider configurations
    dns01:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:
        - name: route53
          route53:
            region: eu-west-1

            accessKeyID: ${aws_access_key_id}
            secretAccessKeySecretRef:
              name: route53-credentials-${domain}
              key: secret
